function updateEverything(changedModule = null) {
    constrainStructure(changedModule);
    constrainStress(changedModule);
    updateArea();
    updateHabitatPreview();
    updateHoopStress();
    updateWaterPressure();
    updateSubstratePressure();
    updateElevationPressure();
    updateAirDepth();
    updateAirPressure();
    updateTotalStress();
    updateTrueArea();
    updateSeaLevelGravity();
    updateMountainGravity();
    updateLayerPreview();
    updateRP();
    updateConfigurationCode();
}